### 원-핫 인코딩 
```txt
OneHotEncoder : 범주형 데이터(문자, 카테고리)를 숫자로 바꿔주는 도구
머신러닝 모델(예: 회귀, 분류 알고리즘)은 대부분 문자 데이터를 직접 이해 못 함.
그래서 문자(France, Spain, ,,,)를 숫자로 바꿔줘야 하는데 단순히 1,2,3번호로 바꾸면
순서가 있다 라고 잘못 이해할 수 있음.
따라서 OneHotEncoder로 각각 독립적인 열로 변환하는게 안전함.
예를 들면:
- France : (1,0)(0,0)(0,0)
- Spain : (0,0)(1,0)(0,0)
- Germany : (0,0)(0,0)(1,0)
```

In [1]:
import pandas as pd

데이터 분석과정 - 데이터 준비<br>
데이터 불러오기<br>
형태 파악하기<br>

In [2]:
df = pd.read_csv("../data/Data.csv")
X = df.iloc[:, :-1].values 
y = df.iloc[:,-1].to_numpy()
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No'
 'Yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

In [3]:
import numpy as np
# 데이터셋에서 결측값을 처리하는데 사용되는 클래스
from sklearn.impute import SimpleImputer
# 객체 생성 - 파라미터 선택가능한지
# 두 번째는 결측치에 옵션을 선택
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X[:, 1:3])


,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'mean'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If a feature has nomissing values at fit/train time, the feature won't appear onthe missing indicator even if there are missing values attransform/test time.",False
,"keep_empty_features keep_empty_features: bool, default=FalseIf True, features that consist exclusively of missing values when`fit` is called are returned in results when `transform` is called.The imputed value is always `0` except when `strategy=""constant""`in which case `fill_value` will be used instead... versionadded:: 1.2",False


In [4]:
# 머신러닝에서 fit함수를 호출하는 건 학습을 의미함
# X 데이터의 1번열과 2번열을 대상으로 SimpleImputer를 학습함.
# fit함수는 주어진 열에서 결측값을 처리하기 위한 정보를 수집함
# 해당 열에 평균 값을 계산함.
#imputer.fit(X[:, 1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
# 원-핫 인코딩: 범주형 열만 숫자 열 여러 개로 변환하기
from sklearn.preprocessing import OneHotEncoder
# ColumnTransformer: 열별로 다른 변환 적용가능함.
from sklearn.compose import ColumnTransformer
# transformers=[(이름, 변환기, 적용할 열 인덱스),....]
# remainder = "passthrough" -> 변환하지 않은 나머지 열은 그대로 뒤에 붙임. 
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder="passthrough")
# fit_transform: 0번 열의 범주를 학습하고 원-핫 변환 + 나머지 열 결합
# 반환값은 희소행렬이므로 np.array로 배열화 시킴.
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### 데이터 분리
```txt
Kaggle 타이타닉 생존 예측(전형적으로 쓰이는 구성)
1. train.csv(80%) - 정답이 있는 학습용 데이터
- 모델을 학습시키는 데이터
- 입력값(Feature) + 정답(Label) 함께 들어있음
- 정답 컬럼이 들어있음 - Survived
2. test.csv(20%) - 정답이 없는 시험 데이터 - Survived가 없음
- 실제 예측 대상 데이터들
- train.csv로 학습한 모델을 사용해서 Survived를 예측해야 함.
- 정답 컬럼이 없음
3. gender_submission
- 제출 양식 예시 - 제출파일이다.
- 승객 ID, 예측한 생존 여부(0/1)

흐름
1.train.csv로
- X(특징들)/y(정답-Survived)분리
- 전처리(결측치, 원핫인코딩,,,등)
- 모델 학습
2.test.csv에
- train과 동일한 전처리 적용
- 모델로 Survived예측
3.제출 파일 생성
```

train_test_split함수를 사용하기<br>
결측치와 범주형 데이터를 수치형으로 인코딩한 후에 값이 함수 파라미터로 사용됨

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
X_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [8]:
y_train

array(['Yes',
       'Yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

In [9]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [10]:
y_test

array(['No', 'No'], dtype=object)