### Feature Scaling ( 특성 스케일링 )
```text
Feature Scaling이란?
서로 다른 크기의 숫자 데이터를 비슷한 범위로 맞추는 작업이다.

왜 필요한가?
키와 연봉을 비교해 보면....
키(cm): 170cm, 180cm
연봉(만원): 3500, 4200

문제 발생 제기
머신러닝 모델은 숫자가 큰 변수를 더 중요하게 인식하는 경향이 있다.
- 거리계산
- KNN
- 경사하강법
- SVM
- 신경망

단 의사결정나무나 랜덤포래스트에서는 필요없음
```

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [5]:
data = np.array([[170, 3500], [180,4200]])
data

array([[ 170, 3500],
       [ 180, 4200]])

In [7]:
scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)

```txt
data : 2행 2열 - 1열 키(170,180), 2열 연봉(3500, 4200): 단위-범위가 다름
MinMaxScaler() : 각 열을 최소값 0, 최대값 1호 스케일링함
수식: (X-min) / ( max-min )
fit_transform(data) : 각 열의 min-max를 구한 뒤 위 식으로 변환
1열: 170 -> 0, 180 -> 2열: 3500 -> 0, 4200 -> 1
scaled: [[0.,0.], [1., 1.]] 형태. 즉 모든 값이 0~1 사이로 정규화 됨
결론:
키와 연봉처럼 단위가 다른 특성을 0~1 구간으로 맞춰,  모델이 한 특성이 과하게 의존하지 않도록 함.
```

In [8]:
print(scaled)

[[0. 0.]
 [1. 1.]]


- 정규화 - 해석이 쉬움, 이미지 데이터에 많이 사용

표준화<br>
수식: (x - mean(x)) / std(x)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled = scaler.fit_transform(data)
print(scaled)

[[-1. -1.]
 [ 1.  1.]]


- 표준화 - 가장 많이 사용. 음수값 가능,  신경망/ 로지스틱 회귀에 적합

- Robust Scalling( 이상치에 강함 )