## 데이터 전처리
1. 결측치 처리
2. 원-핫 인코딩
3. 특성스케일링

In [25]:
import pandas as pd
import numpy as np

#STEP1 - 결측치 처리

In [26]:
# df = pd.read_csv("../data/titanic/test.csv")
df = pd.read_csv("../data/Data.csv")
# 변수 X는 독립변수 불러오기 - iloc
X = df.iloc[:,:-1].values
y = df.iloc[:,-1]

In [27]:
df.fillna(value=df['Salary'].mean())

,Country,Age,Salary,Purchased
0,France,44.000000,72000.000000,No
1,Spain,27.000000,48000.000000,Yes
2,Germany,30.000000,54000.000000,No
3,Spain,38.000000,61000.000000,No
4,Germany,40.000000,63777.777778,Yes
5,France,35.000000,58000.000000,Yes
6,Spain,63777.777778,52000.000000,No
7,France,48.000000,79000.000000,Yes
8,Germany,50.000000,83000.000000,No
9,France,37.000000,67000.000000,Yes ...


In [37]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [35]:
# 결측치를 중앙값을 처리할 때는 - median
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [38]:
# 결측치를 최빈값을 처리할 때는 - most_frequent
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


STEP#2 원-핫 인코딩
- 머신러닝 모델은 숫자만 이해함.
- 성별을 0과 1로 바꿀 수 있다. -> 숫자는 순서가 있다.

In [30]:
df = pd.read_csv("../data/Data.csv")
X = df.iloc[:,:-1].values

In [31]:
#!~ 범주형( 국적 ) 열만 숫자 열 여러개로 변환
from sklearn.preprocessing import OneHotEncoder
# 연별로 다른 변환 적용
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


STEP#3. 특성 스케일링
```txt
1. 정규화: -1 ~ 1 ( 구간 )
  : 보통 많이 사용함
  : 신경망/ 로지스틱 회귀 적합
2. 표준화: 0 ~ 1 ( 구간 )
  : 170 -> 0, 3500 -> 0표시
  : 180 -> 1, 4200 -> 1표시
3. Robust Scaling( 이상치게 강함 )
```

In [32]:
from sklearn.preprocessing import StandardScaler
import numpy as np
data = np.array([[170, 3500],
                [180, 4200]])
scaler = StandardScaler()
scaled = scaler.fit_transform(data)
print(scaled)

[[-1. -1.]
 [ 1.  1.]]
